### ISSUE TITLE
Question: landscape and portrait handling

### ISSUE THREAD

**Issue by sasnik** [shogo4405/GPUHaishinKit.swift#1]
Is it possible to stream for landscape ?

I have been playing around for many hours and still can't get the right result.
Im using:
```rtmpStream?.syncOrientation = true```

and im listening to device orientation changes.

```
    func rotated() {
        switch UIDevice.current.orientation {
        case .landscapeRight:
            rtmpStream?.videoSettings = [
                "width": 1280, // video output width
                "height": 720, // video output height
            ]
        case .landscapeLeft:
            rtmpStream?.videoSettings = [
                "width": 1280, // video output width
                "height": 720, // video output height
            ]
        default:
            rtmpStream?.videoSettings = [
                "width": 720, // video output width
                "height": 1280, // video output height
            ]
        }
    }
```

chaning rtmpStream.orientation doesnt seem to work.

Please see attached image.

![screen shot 2017-03-15 at 19 06 16](https://cloud.githubusercontent.com/assets/10949994/23961136/aace9b00-09b2-11e7-8137-59cf8f297bbb.png)

**Comment by omarojo** [comment]
You cannot change the video aspect ratio / dimensions of the video once the stream has started. If you start in portrait it will stay portrait.

Although the actual content of the video may respond to orientstion changes, so its always straight, but the content might get stretched to fill the video wether portrsit or landscspe
