### ISSUE TITLE
Question: Has anyone been able to successfully stream to Twitch using this framework?

### ISSUE THREAD

**Issue by PeteyCodes** [shogo4405/GPUHaishinKit.swift#2]
I have tried a number of times with several different settings to stream to Twitch, but all attempts seem to fail. It establishes a connection and starts sending packets, only to get disconnected after about 15 seconds or so. 

Has anyone else seen this behavior, and if so, have you managed to correct it?

Thanks in advance.

**Comment by shogo4405** [comment]
@PeteyCodes 
Yes. I'm testing now. works fine. 15 seconds... Default timeout settings is 15 seconds.
* Server lists are here: https://twitchstatus.com/ 

```
rtmpConnect.connect("rtmp://live-tyo.twitch.tv/app")
netStream.publish("_YourStreamKey_")
```

Best, Regards.

**Comment by PeteyCodes** [comment]
Ah - I didn't realize that the string supplied to the publish call was the stream key - I was adding it to the end of the URL in the connect call. 

All seems to be working now! Thanks for the quick reply!
