### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by matthijsotterloo** [shogo4405/GPUHaishinKit.swift#3]
My app is crashing on this line:

`dispatch_sync(videoProcessingQueue, block);` in `GPUImageOutput.m` with the following error: `_deque_insertObjectAtIndex: object cannot be nil'` any clue what it could be?

**Comment by shogo4405** [comment]
Could you be more specific? I want to see your code.
And please use this github issues. https://github.com/shogo4405/lf.swift/issues.
